name: CI

on:
  push:
    branches:
      - master

jobs:
  build-on-linux:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Nix build
        run: |
          nix build
