name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Nix build
        run: |
          nix build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: ws-access-token-macos
          path: ./result/bin/ws-access-token
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ws-access-token-macos
      - name: Test
        run: |
          ls
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            ws-access-token
